version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my-laravel-app
        volumes:
            - ./../:/var/www/html
        ports:
            - "127.0.0.1:80:80"
        stdin_open: true
        tty: true
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: mysql
        container_name: mysql-laravel
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: vaii_lackom
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_PASSWORD: pass987word
            MYSQL_USER: us987er
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "127.0.0.1:3306:3306"
        networks:
            - laravel-network

    adminer:
        links:
            - db
        depends_on:
            - db
        image: adminer
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db

networks:
    laravel-network:
        driver: bridge
